application: anticipate

# Version 0.0.0
version: v0-0-0
api_version: 1
runtime: python27
threadsafe: true


handlers:

# Endpoints API
- url: /_ah/spi/.*
  script: api.application

# Garbage collectors
- url: /_ah/garbagecollect/.*
  script: api.garbagecollect.collectors
  login: admin

# OAuth2 redirect handlers
- url: /oauth2/.*
  script: api.auth.redirect_handlers

# Web client resources
- url: /res
  static_dir: bower_components

# Web client pages
#-url: /


libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
- name: webapp2
  version: latest
