application: dhsdev-ticktock

# Version 0.0.0
version: v0-0-0
api_version: 1
runtime: python27
threadsafe: true


handlers:

# Endpoints API
- url: /_ah/spi/.*
  script: api.server

# Garbage collectors
- url: /_ah/garbagecollect/.*
  script: api.garbagecollect.collectors
  login: admin

# API explorer redirect
- url: /
  script: api.explorer_redirect


libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
- name: webapp2
  version: latest
