application: anticipate

# Version 0.0.0
version: v0-0-0
api_version: 1
runtime: python27
threadsafe: true


handlers:

# Endpoints api
- url: /_ah/spi/.*
  script: api.application

# Web client resources
- url: /res
  static_dir: bower_components


libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
- name: webapp2
  version: latest
