application: dhsdev-ticktock

# Version 0.2.0
version: v0-2-0
api_version: 1
runtime: python27
threadsafe: true


handlers:

# Endpoints API
- url: /_ah/spi/.*
  script: api.server

# Garbage collectors
- url: /_ah/garbagecollect/.*
  script: api.garbagecollect.collectors
  login: admin

# Web App
- url: /
  static_files: dist/index.html
  upload: dist/index\.html
- url: /
  static_dir: dist


skip_files:

# Defaults
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$

# Private Key Files
- ^(.*/)?.*\.pem$
- ^(.*/)?.*\.p12$

# Dev Extras
- ^node_modules/.*$
- ^bower_components/.*$
- ^app/.*$
- ^package\.json$
- ^bower\.json$
- ^gulpfile\.js$
- ^wct\.conf\.js$
- ^requirements\.txt$


libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
- name: webapp2
  version: latest
